"""adding columns

Revision ID: 2e0caf2dd52b
Revises: edac8b8a306f
Create Date: 2025-10-01 09:50:42.204162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e0caf2dd52b'
down_revision = 'edac8b8a306f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_comments',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('draft_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('summary', mysql.TEXT(), nullable=True),
    sa.Column('sentiment_label', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('sentiment_score', mysql.FLOAT(), nullable=True),
    sa.Column('section', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('article', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('chapter', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('datetime', mysql.DATETIME(), nullable=True),
    sa.Column('comment_datetime', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], name=op.f('processed_comments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
