"""adding columns

Revision ID: edac8b8a306f
Revises: 0290af7f8933
Create Date: 2025-09-29 23:18:45.113463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edac8b8a306f'
down_revision = '0290af7f8933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_file', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('processing', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.drop_column('processing')
        batch_op.drop_column('result_file')

    # ### end Alembic commands ###
